version: '3.8'

services:
  frontend:

    image: kunfi/frontend
    container_name: frontend_kunfi
    depends_on:
      - backend
    ports:
      - 8001:3000
    env_file: 
      - .env
  backend:

    image: kunfi/backend
    container_name: backend_kunfi
    depends_on:
      - db
    ports:
      - 8086:8086
    env_file: 
      - .env

  db:

    image: 'postgres:10-alpine'
    container_name: dbkunfi
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
